version: '3.8'

services:
  db:
    image: postgres:15
    container_name: prol-educa-db
    restart: always
    environment:
      POSTGRES_DB: proleduca
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    networks:
      - prol-educa-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: prol-educa
    container_name: prol-educa-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/proleduca
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      JWT_SECRET: mySimpleSecretKey123!
      JWT_EXPIRATION_MS: 3600000
      APP_REFRESHEXPIRATION: 21600
    networks:
      - prol-educa-network

volumes:
  postgres_data:

networks:
  prol-educa-network:
